JIRA_BASE_URL = "https://creatiefstudio.atlassian.net"
JIRA_EMAIL = "creatiefstudiodigital@gmail.com"
JIRA_API_TOKEN = "ATATT3xFfGF0CHE6cbyQo6p_MZbhuEXyca4MNndkIyud8gO8QQeynpFEmxEpUZHCl7KkSxJw1nbovYOblyITU1KzQ5jiWlDV1gWarBGHPsNjrzilI80mCAntE_iYmxKclecaAWZE5mOFTgALuZf1QV1r-EbO4Yu6xRv6dNmWL32H_4T8TSSlUaY=0AAE2EFC"
JIRA_PROJECT_KEY = "CS"

OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4o-mini"

# Opcionales:
JIRA_DRY_RUN = "1"

